
mpesa.consumer-key=NhnACQzYGhhwMct5RJoTgYImL1QsOGZ1w44y9R40X9i34M0q
mpesa.consumer-secret=rCoEMUrrVGfoDO5AZwvtpZmts1saHU1ViaxDg33IlE4923sXa56RbXWcMjDpk60n
mpesa.passkey=e5b2ec3973c8aad9e2072db8e45011e3fdda7aa6a24717699c9df1345aec8f3e
mpesa.security-credential=DE2QlGX+4wFOgM/s8zf4nXPMAmKnc8ad4+SA/NGhTacuispUnD0bxsOep1ljs3zw3D3qviH5TweH1NarHEQEImhG4aGF3Al9F+Uaw1iuNsaruk2UVAAOA6E7iJSIqTmaBFCunrBUG2G62xf6ek+ixH55wVN+U9fwbpwnR7zD/AnGmylrWeGkJ/8t4Z7lZMlFrNDIvhNuZ6WOHq3dC7UetpPpXA9qgS/Y5wIjKTp68VliN8cxYXRJyXUXfcamhBHF2nFyFORQ0zxvIuB4uspn9VA9LSdJwxhzewnNy5xm8XXoyC7MGsb5PifgCt3gFrv1mO4sSPcKPlVwKNsd1hgs6w==
mpesa.account-ref="TRIBE_SYSTEMS"

mpesa.shortcode=4885139
mpesa.org-shortcode=4885139
mpesa.till-number=9359644
mpesa.callback-url=https://payment.tribessystems.co.ke/api/v1/payment/callback
mpesa.confirm-result-url=https://payment.tribessystems.co.ke/api/v1/payment/confirm/result
mpesa.confirm-timeout-url=https://payment.tribessystems.co.ke/api/v1/payment/confirm/timeout

#C2B
mpesa.c2b-validation-callback=https://payment.tribessystems.co.ke/api/v1/payment/c2b/validation
mpesa.c2b-confirmation-callback=https://payment.tribessystems.co.ke/api/v1/payment/c2b/confirmation

#B2C
mpesa.b2c-result-callback=https://payment.tribessystems.co.ke/api/v1/payment/b2c/result
mpesa.b2c-timeout-callback=https://payment.tribessystems.co.ke/api/v1/payment/b2c/timeout

#B2B
mpesa.b2b-callback-url=https://payment.tribessystems.co.ke/api/v1/payment/b2b/callback
mpesa.b2b-merchant-name=ASANO

mpesa.auth-url=https://api.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials
mpesa.initiate-stk-push-url=https://api.safaricom.co.ke/mpesa/stkpush/v1/processrequest
mpesa.check-stk-push-txn-url=https://api.safaricom.co.ke/mpesa/stkpushquery/v1/query
mpesa.query-txn-status=https://api.safaricom.co.ke/mpesa/transactionstatus/v1/query

#C2B
mpesa.register-c-to-b-callback-url=https://api.safaricom.co.ke/mpesa/c2b/v2/registerurl
mpesa.simulate-c-to-b-transaction=https://sandbox.safaricom.co.ke/mpesa/c2b/v2/simulate

#B2C
mpesa.b-to-c-url=https://api.safaricom.co.ke/mpesa/b2c/v1/paymentrequest
mpesa.b-to-c-api-username=TRIBE

#B2B
mpesa.b-to-b-url=https://api.safaricom.co.ke/mpesa/b2b/v1/paymentrequest

payment.secret-key=secret-key-for-password-hashing
payment.jwt-issuer-name=tribe-systems-security

springdoc.swagger-ui.path=/swagger-ui
logging.file.path=/logs/tribe_payment
